#!/usr/bin/env python3
"""Emit the recon artefacts for 2026-09-05-reflection-eye-field-hunt."""
import json, re, os, io

OUT = r"C:\Users\TD3KX\github-backups-pd\doom-2016-vr\dev-archive\recon\2026-09-05-reflection-eye-field-hunt"
os.makedirs(OUT, exist_ok=True)

db = json.load(open("db.json"))
byname = {c["name"]: c for c in db}
runs = json.load(open("runs.json"))
F = [f for r in runs for f in r["fields"]]

HDR = ("# Generated by dev-archive/recon/2026-09-05-reflection-eye-field-hunt/tools/\n"
       "# Source: DOOMx64vk.exe (DOOM 2016), read-only static PE parse. The game was\n"
       "# NOT launched and nothing was run. Field names / types / offsets are interface\n"
       "# metadata, not game content.\n")

def dump_class(c):
    s = io.StringIO()
    s.write("=== %s   sizeof=%d   reflected fields=%d\n" % (c["name"], c["sizeof"], c["n"]))
    s.write("    class descriptor VA 0x%x   field table VA 0x%x\n\n" % (c["va"], c["table"]))
    for f in c["fields"]:
        s.write("  +%-6d  sz=%-6d  %s%s %s\n" % (f["off"], f["size"], f["type"], f["suffix"], f["name"]))
        if f["comment"]:
            for line in [f["comment"][i:i + 100] for i in range(0, len(f["comment"]), 100)]:
                s.write("              // %s\n" % line)
    s.write("\n")
    return s.getvalue()

# --- 1. the view family ------------------------------------------------------
fam = ["renderView_t", "idRenderView", "idScreenView", "idRenderFrameInfo",
       "idViewBypass", "idView", "idAutoMapParms_t", "envBlend_t", "envBlendParms_t"]
with open(os.path.join(OUT, "view-family-fields.txt"), "w", encoding="utf-8") as fh:
    fh.write(HDR)
    fh.write("# The complete reflected field listing for every class in DOOM 2016's view\n"
             "# chain, root first. Read renderView_t -> idRenderView -> idScreenView ->\n"
             "# idRenderFrameInfo: that is the containment order the renderer walks.\n\n")
    for n in fam:
        if n in byname:
            fh.write(dump_class(byname[n]))

# --- 2. the eye/stereo census ------------------------------------------------
pats = [
    ("field name contains 'stereo' / 'steroe'", r'stereo|steroe'),
    ("field name contains 'eye'", r'eye'),
    ("field name contains 'ipd' / 'interpupil' / 'interocul'", r'ipd|interpupil|interocul'),
    ("field name contains 'parallax' / 'converg'", r'parallax|converg'),
    ("field name contains 'hmd' / 'headmount'", r'hmd|headmount'),
    ("field name contains 'oculus' / 'vive' / 'openvr' / 'ovr'", r'oculus|vive|openvr|\bovr\b'),
    ("field name contains 'separation'", r'separation'),
    ("field name contains 'binocular' / 'monoscop' / 'stereoscop'", r'binocular|monoscop|stereoscop'),
]
with open(os.path.join(OUT, "eye-stereo-census.txt"), "w", encoding="utf-8") as fh:
    fh.write(HDR)
    fh.write("\n# CENSUS over EVERY 72-byte reflection field record in .data.\n"
             "# records walked: %d\n"
             "# records the same scan finds with the string-pointer test widened to\n"
             "#   .rdata|.data (i.e. the ceiling on what this shape can find): 57228\n"
             "# => coverage 57214/57228 = 99.98%%. Widening the filter moved the count by 0.\n\n" % len(F))
    for label, p in pats:
        rx = re.compile(p, re.I)
        hits = [f for f in F if rx.search(f["name"])]
        fh.write("--- %-56s %d hit(s)\n" % (label, len(hits)))
        seen = set()
        for f in hits:
            k = (f["type"], f["suffix"], f["name"])
            if k in seen:
                continue
            seen.add(k)
            fh.write("      %-44s %s\n" % (f["type"] + f["suffix"], f["name"]))
        fh.write("\n")
    fh.write("\n# EVERY record whose DEVELOPER COMMENT mentions stereo (the second search\n"
             "# surface: the reflection DB carries id's own doc comments).\n\n")
    rxc = re.compile(r'stereo|steroe', re.I)
    for f in F:
        if f["comment"] and rxc.search(f["comment"]):
            fh.write("  %s %s\n      // %s\n\n" % (f["type"] + f["suffix"], f["name"], f["comment"]))

# --- 3. full class index -----------------------------------------------------
with open(os.path.join(OUT, "class-index.txt"), "w", encoding="utf-8") as fh:
    fh.write(HDR)
    fh.write("# Every class the reflection database names, with its sizeof and its number\n"
             "# of reflected fields. sizeof comes from the class descriptor, not inferred.\n"
             "# classes: %d   reflected fields reachable from them: %d\n\n"
             "# %-70s %-9s %-6s %s\n" % (len(db), sum(c["n"] for c in db),
                                          "class", "sizeof", "n", "field table VA"))
    for c in sorted(db, key=lambda c: c["name"]):
        fh.write("  %-70s %-9d %-6d 0x%x\n" % (c["name"], c["sizeof"], c["n"], c["table"]))

# --- 4. the camera/view/render class subset ---------------------------------
rx = re.compile(r'(view|render|camera|^cam|projection|frustum)', re.I)
with open(os.path.join(OUT, "camera-view-classes.txt"), "w", encoding="utf-8") as fh:
    fh.write(HDR)
    fh.write("\n# The %d classes whose NAME contains view/render/camera/projection/frustum.\n"
             "# This is the shortlist a future pass should dump in full if it needs more\n"
             "# than the view chain in view-family-fields.txt.\n\n"
             % len([c for c in db if rx.search(c["name"])]))
    for c in sorted([c for c in db if rx.search(c["name"])], key=lambda c: c["name"]):
        fh.write("  %-70s sizeof=%-8d n=%-5d tbl=0x%x\n" % (c["name"], c["sizeof"], c["n"], c["table"]))

print("written to", OUT)
for f in sorted(os.listdir(OUT)):
    p = os.path.join(OUT, f)
    if os.path.isfile(p):
        print("  %-30s %d bytes" % (f, os.path.getsize(p)))
